const FALTAN_DATOS = "Faltan datos obligatorios";
const ESTADO_OK = "OK";
const ESTADO_ERROR = "FALLO";
const FALTA_ID_USUARIO = "FALTA ID DEL USUARIO";
const FALTA_ID_CARRERA = "FALTA ID DE LA CARRERA";
const FALTA_ID_MATERIA = "FALTA ID DE LA MATERIA";
const FALTA_ID_ESTUDIANTE = "FALTA ID DEL ESTUDIANTE";
const FALTA_ID_NACIONALIDAD = "FALTA ID DE NACIONALIDAD";
const USUARIO_EXISTENTE = "El usuario ya existe en la base";



module.exports = {
    FALTAN_DATOS,
    ESTADO_OK,
    ESTADO_ERROR,
    FALTA_ID_USUARIO,
    FALTA_ID_CARRERA,
    FALTA_ID_MATERIA,
    FALTA_ID_ESTUDIANTE,
    FALTA_ID_NACIONALIDAD,
    USUARIO_EXISTENTE
};