const FALTAN_DATOS = "Faltan datos obligatorios";
const ESTADO_OK = "OK";
const ESTADO_ERROR = "FALLO";
const ESTADO_SIN_PERMISOS = "SIN PERMISOS";
const FALTA_ID_USUARIO = "FALTA ID DEL USUARIO";
const FALTA_ID_CARRERA = "FALTA ID DE LA CARRERA";
const FALTA_ID_MATERIA = "FALTA ID DE LA MATERIA";
const FALTA_ID_ESTUDIANTE = "FALTA ID DEL ESTUDIANTE";
const FALTA_ID_INSCRIPCION_MATERIA = "FALTA ID INSCRIPCION MATERIA";
const FALTA_ID_INSCRIPCION_CARRERA = "FALTA ID INSCRIPCION CARRERA";
const FALTA_ID_NACIONALIDAD = "FALTA ID DE NACIONALIDAD";
const USUARIO_EXISTENTE = "El usuario ya existe en la base";
const ESTUDIANTE_SIN_CARRERA = "Estudiante no registrado en la carrera o inactivo";


module.exports = {
    FALTAN_DATOS,
    ESTADO_OK,
    ESTADO_ERROR,
    ESTADO_SIN_PERMISOS,
    FALTA_ID_USUARIO,
    FALTA_ID_CARRERA,
    FALTA_ID_MATERIA,
    FALTA_ID_INSCRIPCION_MATERIA,
    FALTA_ID_INSCRIPCION_CARRERA,
    FALTA_ID_ESTUDIANTE,
    FALTA_ID_NACIONALIDAD,
    USUARIO_EXISTENTE,
    ESTUDIANTE_SIN_CARRERA
};